# Hardware configuration template for farnsworth
# This file is generated by nixos-generate-config and should be replaced
# with the actual hardware configuration during installation

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # NOTE: This is a template. Replace with actual values during installation
  # Run: nixos-generate-config --root /mnt --show-hardware-config
  
  # Boot configuration is in default.nix
  
  # Filesystems are configured via disko.nix
  # Hardware-specific mounts will be added here by nixos-generate-config
  
  # Hardware-specific settings
  hardware.cpu.intel.updateMicrocode = lib.mkDefault true;
  hardware.cpu.amd.updateMicrocode = lib.mkDefault true;
  
  # Enable hardware acceleration
  hardware.opengl = {
    enable = true;
    driSupport = true;
    driSupport32Bit = true;
  };
  
  # Note: GPU drivers are configured in modules/nixos/hardware/
}

